Feature/cgi
tredfort/webserv pull request #46
Opened 2022-05-31 17:12 UTC by chudopak

CGI работает с простыми файлами. Надо добавить env какие-то странные.

2022-05-31 20:58 UTC, tredfort commented on srcs/requestHandler/RequestHandler.cpp
> +	CGI cgi = CGI(pathToFile, env);
Я бы, CGI создавал единожды в конструкторе  в момент создания RequestHandler, далее юзал бы метод его методы, это не юзер, который приходит и уходит, а инструмент сервера.

2022-05-31 21:10 UTC, tredfort commented on srcs/CGI/CGI.cpp
> +	if (!isFileExists(_pathToExecFile)) {
Наверное, тебе проверки и не надо делать. Нужно же еще индексные файлы, если будут php через через cgi  прогнать

2022-06-02 16:00 UTC, Dmi3Iva commented on srcs/requestHandler/RequestHandler.cpp
> +	CGI cgi = CGI(pathToFile, env);
Решили на том, что cgi может не использоваться, поэтому решили оставить так

2022-06-02 16:03 UTC, Dmi3Iva approved these changes
Ну вроде чё-то понятно 😅 В целом вроде окей)

resources/html_data/cgi/fileCgi этот файл можно добавить в gitignore, вообще он пустой, нужен ли он?

2022-06-02 20:00 UTC, tredfort commented on srcs/interfaces/ICGI.hpp
> +class ICGI {
Это я в январе еще когда начинал 2-й раз делать, везде добавил интерфейсы, наверное да, уже не актуально

2022-06-02 20:03 UTC, tredfort commented on srcs/requestHandler/RequestHandler.cpp
> +	CGI cgi = CGI(pathToFile, env);
вот именно, он может и не использоваться, а объекты CGI  будут создаваться на каждый чих

2022-06-03 07:29 UTC, chudopak commented on srcs/interfaces/ICGI.hpp
> +class ICGI {
Смысл в том, что если нужен будет еще один класс CGI, то можно будет хранить только его интерфейс потом. Лучше вообще весь функционал на интерфейсах завязывать))

2022-06-04 14:02 UTC, tredfort requested changes

2022-06-04 14:02 UTC, tredfort commented on srcs/interfaces/IRequestHandler.hpp
> +	virtual void formResponse(Request* request, Response* response, Env& env) = 0;
Нужно Env передать через конструктор, 1 раз при создании  CGI

2022-06-06 18:31 UTC, chudopak commented on srcs/CGI/CGI.cpp
> +	if (!isFileExists(_pathToExecFile)) {
Да, но мне бы нужно откуда-то взять названия файлов, которые есть) Завтра решим

2022-06-06 18:33 UTC, chudopak commented on srcs/interfaces/IRequestHandler.hpp
> +	virtual void formResponse(Request* request, Response* response, Env& env) = 0;
Переделал, сейчас все через конструктор передается

2022-06-09 15:43 UTC, merged